/**
 * Lightweight GitHub REST API Integration Client for Mayank's Patch Engine.
 */

/**
 * Creates a new branch from a base branch and commits a patched file, then opens a PR.
 *
 * @param {Object} params
 * @param {string} params.repoOwner - e.g. "owner"
 * @param {string} params.repoName - e.g. "my-repo"
 * @param {string} [params.baseBranch="main"]
 * @param {string} [params.newBranch] - auto-generated if omitted
 * @param {string} params.filePath - path to file in repo
 * @param {string} params.patchedCode - new file content
 * @param {string} params.commitMessage - commit message
 * @param {string} params.prTitle - PR title
 * @param {string} params.prBody - PR description
 * @param {string} params.githubToken - GitHub Personal Access Token or OAuth token
 * @returns {Promise<{prUrl: string, prNumber: number, branch: string}>}
 */
async function openFixPullRequest({
  repoOwner,
  repoName,
  baseBranch = "main",
  newBranch,
  filePath,
  patchedCode,
  commitMessage,
  prTitle,
  prBody,
  githubToken,
}) {
  if (!githubToken) {
    throw new Error("githubToken is required to open a GitHub Pull Request");
  }

  const branchName = newBranch || `structurai/fix-${Date.now()}`;
  const headers = {
    Authorization: `token ${githubToken}`,
    Accept: "application/vnd.github.v3+json",
    "User-Agent": "StructurAI-PatchEngine",
    "Content-Type": "application/json",
  };

  const baseUrl = `https://api.github.com/repos/${repoOwner}/${repoName}`;

  // 1. Get SHA of base branch
  const refRes = await fetch(`${baseUrl}/git/ref/heads/${baseBranch}`, { headers });
  if (!refRes.ok) {
    const text = await refRes.text();
    throw new Error(`Failed to fetch base branch ref '${baseBranch}': ${text}`);
  }
  const refData = await refRes.json();
  const baseSha = refData.object.sha;

  // 2. Create new branch from base SHA
  const createRefRes = await fetch(`${baseUrl}/git/refs`, {
    method: "POST",
    headers,
    body: JSON.stringify({
      ref: `refs/heads/${branchName}`,
      sha: baseSha,
    }),
  });
  if (!createRefRes.ok) {
    const text = await createRefRes.text();
    throw new Error(`Failed to create branch '${branchName}': ${text}`);
  }

  // 3. Get existing file SHA (if updating)
  let fileSha;
  const fileRes = await fetch(`${baseUrl}/contents/${filePath}?ref=${branchName}`, { headers });
  if (fileRes.ok) {
    const fileData = await fileRes.json();
    fileSha = fileData.sha;
  }

  // 4. Create/update file commit on new branch
  const encodedContent = Buffer.from(patchedCode, "utf-8").toString("base64");
  const updateFileRes = await fetch(`${baseUrl}/contents/${filePath}`, {
    method: "PUT",
    headers,
    body: JSON.stringify({
      message: commitMessage || `fix: AI patch for ${filePath}`,
      content: encodedContent,
      branch: branchName,
      sha: fileSha,
    }),
  });

  if (!updateFileRes.ok) {
    const text = await updateFileRes.text();
    throw new Error(`Failed to commit file '${filePath}': ${text}`);
  }

  // 5. Create Pull Request
  const prRes = await fetch(`${baseUrl}/pulls`, {
    method: "POST",
    headers,
    body: JSON.stringify({
      title: prTitle || `StructurAI Fix: Automated patch for ${filePath}`,
      body: prBody || "Automated patch generated by StructurAI Patch Engine.",
      head: branchName,
      base: baseBranch,
    }),
  });

  if (!prRes.ok) {
    const text = await prRes.text();
    throw new Error(`Failed to create Pull Request: ${text}`);
  }

  const prData = await prRes.json();

  return {
    prUrl: prData.html_url,
    prNumber: prData.number,
    branch: branchName,
  };
}

module.exports = {
  openFixPullRequest,
};
