import { Card, CardHeader, CardTitle, CardContent } from "../components/ui/Card";
import { Badge } from "../components/ui/Badge";
import { Activity, ShieldAlert, Code2, CheckCircle2 } from "lucide-react";
import { AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from "recharts";

const healthData = [
  { name: "Week 1", score: 85 },
  { name: "Week 2", score: 86 },
  { name: "Week 3", score: 84 },
  { name: "Week 4", score: 88 },
  { name: "Week 5", score: 91 },
  { name: "Week 6", score: 92 },
];

export function CodeHealth() {
  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold tracking-tight text-slate-900">Code Health</h1>
        <p className="text-slate-500 mt-1">Continuous scoring and technical debt analysis.</p>
      </div>

      <div className="grid gap-6 md:grid-cols-4">
        <Card className="md:col-span-1 bg-indigo-600 text-white border-indigo-700">
          <CardContent className="p-6">
            <div className="flex items-center justify-between pb-4">
              <p className="text-indigo-100 font-medium">Overall Score</p>
              <Activity className="w-5 h-5 text-indigo-200" />
            </div>
            <div className="flex items-end space-x-2">
              <span className="text-5xl font-bold">92</span>
              <span className="text-indigo-200 text-lg mb-1">/ 100</span>
            </div>
            <p className="text-sm text-indigo-100 mt-4 flex items-center">
              <CheckCircle2 className="w-4 h-4 mr-1" /> Excellent condition
            </p>
          </CardContent>
        </Card>

        <Card className="md:col-span-3">
          <CardHeader className="py-4">
            <CardTitle className="text-sm font-medium text-slate-600">Health Trend (Last 6 Weeks)</CardTitle>
          </CardHeader>
          <CardContent className="h-40 pb-0">
            <ResponsiveContainer width="100%" height="100%">
              <AreaChart data={healthData} margin={{ top: 5, right: 0, left: -25, bottom: 0 }}>
                <defs>
                  <linearGradient id="colorScore" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor="#4f46e5" stopOpacity={0.3}/>
                    <stop offset="95%" stopColor="#4f46e5" stopOpacity={0}/>
                  </linearGradient>
                </defs>
                <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e2e8f0" />
                <XAxis dataKey="name" axisLine={false} tickLine={false} tick={{fill: '#64748b', fontSize: 12}} />
                <YAxis domain={[70, 100]} axisLine={false} tickLine={false} tick={{fill: '#64748b', fontSize: 12}} />
                <Tooltip />
                <Area type="monotone" dataKey="score" stroke="#4f46e5" strokeWidth={3} fillOpacity={1} fill="url(#colorScore)" />
              </AreaChart>
            </ResponsiveContainer>
          </CardContent>
        </Card>
      </div>

      <h2 className="text-lg font-semibold text-slate-900 mt-8 mb-4">Actionable Insights</h2>
      
      <div className="grid gap-6 md:grid-cols-2">
        <Card>
          <CardHeader className="py-4 border-b border-slate-100">
            <CardTitle className="text-base flex items-center">
              <Code2 className="w-4 h-4 mr-2 text-indigo-500" />
              AI Slop Detection
            </CardTitle>
          </CardHeader>
          <CardContent className="pt-4 space-y-4">
            <div className="flex justify-between items-center p-3 bg-slate-50 rounded-lg border border-slate-100">
              <div>
                <p className="text-sm font-medium text-slate-900">Overly generic error handling</p>
                <p className="text-xs text-slate-500 mt-0.5">Found in src/utils/api.ts</p>
              </div>
              <Badge variant="warning">Medium</Badge>
            </div>
            <div className="flex justify-between items-center p-3 bg-slate-50 rounded-lg border border-slate-100">
              <div>
                <p className="text-sm font-medium text-slate-900">Redundant comments generated by Copilot</p>
                <p className="text-xs text-slate-500 mt-0.5">Found in 12 files</p>
              </div>
              <Badge variant="secondary">Low</Badge>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="py-4 border-b border-slate-100">
            <CardTitle className="text-base flex items-center">
              <ShieldAlert className="w-4 h-4 mr-2 text-rose-500" />
              Maintainability Issues
            </CardTitle>
          </CardHeader>
          <CardContent className="pt-4 space-y-4">
            <div className="flex justify-between items-center p-3 bg-rose-50 rounded-lg border border-rose-100">
              <div>
                <p className="text-sm font-medium text-rose-900">High Cyclomatic Complexity (Score: 24)</p>
                <p className="text-xs text-rose-700 mt-0.5">PaymentProcessor.ts</p>
              </div>
              <Badge variant="error">High</Badge>
            </div>
            <div className="flex justify-between items-center p-3 bg-slate-50 rounded-lg border border-slate-100">
              <div>
                <p className="text-sm font-medium text-slate-900">Duplicated Logic (85% match)</p>
                <p className="text-xs text-slate-500 mt-0.5">UserAuth.ts and AdminAuth.ts</p>
              </div>
              <Badge variant="warning">Medium</Badge>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
